version: '3.7'

services:

  rabbitmq:
    image: pcloud/rabbitmq-stomp
    hostname: rabbit
    container_name: rabbitmqs
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Mannul84"
    ports:
      - "15672:15672"
      - "61613:61613"
    networks:
      - backend-network

  backend-g:
    container_name: backend-g
    build: .
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: rabbitmqs
      SPRING_RABBITMQ_USER: "admin"
      SPRING_RABBITMQ_PASSWORD: "Mannul84"
      SPRING_RABBITMQ_PORT: 61613
      app.cors.allowed-origins: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    links:
      - "rabbitmq"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mysql_data: